### PR TITLE
Rewrited and compacted

### PR DESCRIPTION
**Pull request by Dr-Yukon**

### CODE REVIEW

**Comment by glensc** [comment]
Please include purpose to the pull request. And a screenshot before and after?

**Comment by Dr-Yukon** [comment]
margin: 1em;
margin-left: auto;
margin-right: auto;
=
margin: 1em auto;
https://developer.mozilla.org/en-US/docs/Web/CSS/margin
It is a shorthand for margin-top, margin-right, margin-bottom, and margin-left.

**Comment by Dr-Yukon** [comment]
background-position: 10px 50%; background-repeat: no-repeat; background-color: #B5E0FF; background-image: url(images/important_small.png); = background: #B5E0FF url(images/important_small.png) 10px 50% no-repeat;

https://developer.mozilla.org/en-US/docs/Web/CSS/background
The property is a shorthand that sets the following properties in a single declaration: background-clip, background-color, background-image, background-origin, background-position, background-repeat, background-size, and background-attachment.

**Comment by glensc** [comment]
Have to close the PR if the purpose of the PR is not explained.

**Pull request closed without merging**
