### PR TITLE
Add references metadata

### PR DESCRIPTION
**Pull request by alexdraconian**
Add redirection target as internal link in metadata, to giving hints to other plugins. (Such as backlinks, orphanswanted)

### CODE REVIEW

**Comment by glensc** [comment]
can you amend the commit with the same detailed description as pr title/body?

**Comment by alexdraconian** [comment]
Tried to re-commit and squash, but Github Desktop seems gone wrong... Sorry. At least last commit was pushed as intended.

**Comment by glensc** [comment]
no this is wrong. now you have three commits in the PR. see yourself the Commits tab.

you should git rebase -i and remove the superfluous commits. and then force push.

but since you created the PR from your master branch this will likely fail somewhere.


so maybe easier to create new branch and new pull request. rebase to remove superfluous commits or create from origin/master and cherry pick only fea72f00916e5d47aef0664a056bf01a72c27f76

**Comment by glensc** [comment]
replaced by https://github.com/glensc/dokuwiki-plugin-pageredirect/pull/39

**Pull request closed without merging**
